name: Create S3 Bucket

on:
  workflow_dispatch:
    inputs:
      bucket_name:
        description: 'Name of the S3 bucket (must be globally unique)'
        required: true
        default: 'my-s3-bucket'

jobs:
  create-s3-bucket:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Replace with your desired AWS region

      # Step 3: Create S3 Bucket
      - name: Create S3 Bucket
        run: |
          aws s3api create-bucket --bucket ${{ github.event.inputs.bucket_name }} --region us-east-1 --create-bucket-configuration LocationConstraint=us-east-1